import unreal
root='/Game/Effects/LavaGround/'
levels=unreal.get_editor_subsystem(unreal.LevelEditorSubsystem)
actors=unreal.get_editor_subsystem(unreal.EditorActorSubsystem)
assert unreal.load_asset(root+'NS_LavaGround') and unreal.load_asset(root+'NS_LavaImpactBurst')
assert levels.new_level(root+'L_LavaImpactGround_Preview')
tools=unreal.AssetToolsHelpers.get_asset_tools()
mat=tools.create_asset('M_LavaPreviewFloor',root.rstrip('/'),unreal.Material,unreal.MaterialFactoryNew())
lib=unreal.MaterialEditingLibrary
uv=lib.create_material_expression(mat,unreal.MaterialExpressionTextureCoordinate)
custom=lib.create_material_expression(mat,unreal.MaterialExpressionCustom)
custom.set_editor_property('code','float2 p=UV*36;float2 g=abs(frac(p)-.5);float gridMask=1-smoothstep(.008,.018,min(g.x,g.y));return lerp(float3(.028,.033,.041),float3(.065,.075,.085),gridMask);')
custom.set_editor_property('output_type',unreal.CustomMaterialOutputType.CMOT_FLOAT3)
inp=unreal.CustomInput();inp.set_editor_property('input_name','UV');custom.set_editor_property('inputs',[inp])
lib.connect_material_expressions(uv,'',custom,'UV')
lib.connect_material_property(custom,'',unreal.MaterialProperty.MP_BASE_COLOR)
rough=lib.create_material_expression(mat,unreal.MaterialExpressionConstant);rough.set_editor_property('r',.92)
lib.connect_material_property(rough,'',unreal.MaterialProperty.MP_ROUGHNESS)
lib.recompile_material(mat)
floor=actors.spawn_actor_from_class(unreal.StaticMeshActor,unreal.Vector(0,0,-5))
floor.set_actor_label('NeutralGround_RefractionGrid')
mc=floor.get_component_by_class(unreal.StaticMeshComponent)
mc.set_static_mesh(unreal.load_asset('/Engine/BasicShapes/Plane'))
mc.set_material(0,mat);floor.set_actor_scale3d(unreal.Vector(36,36,1))
for name,label in [('NS_LavaImpactBurst_PreviewLoop','01_ImpactBurst_Independent'),('NS_LavaGround_PreviewLoop','02_LavaGround_Independent')]:
    actor=actors.spawn_actor_from_class(unreal.NiagaraActor,unreal.Vector())
    actor.set_actor_label(label)
    component=actor.get_component_by_class(unreal.NiagaraComponent)
    component.set_asset(unreal.load_asset(root+name));component.activate(True)
light=actors.spawn_actor_from_class(unreal.DirectionalLight,unreal.Vector(0,-300,500),unreal.Rotator(pitch=-50,yaw=30,roll=0))
light.set_actor_label('SoftKeyLight')
lc=light.get_component_by_class(unreal.DirectionalLightComponent)
lc.set_intensity(3.5);lc.set_editor_property('light_source_angle',10)
sky=actors.spawn_actor_from_class(unreal.SkyLight,unreal.Vector(0,0,500))
sky.get_component_by_class(unreal.SkyLightComponent).set_intensity(.7)
pp=actors.spawn_actor_from_class(unreal.PostProcessVolume,unreal.Vector())
pp.set_editor_property('unbound',True)
settings=pp.get_editor_property('settings')
for prop,value in [('override_auto_exposure_method',True),('auto_exposure_method',unreal.AutoExposureMethod.AEM_MANUAL),('override_auto_exposure_bias',True),('auto_exposure_bias',8.0),('override_bloom_intensity',True),('bloom_intensity',.35),('override_motion_blur_amount',True),('motion_blur_amount',0.0)]:settings.set_editor_property(prop,value)
pp.set_editor_property('settings',settings)
unreal.EditorLevelLibrary.set_level_viewport_camera_info(unreal.Vector(570,-760,820),unreal.Rotator(pitch=-41,yaw=127,roll=0))
levels.save_current_level();unreal.EditorAssetLibrary.save_directory(root)
print('PREVIEW_READY: two independent Niagara actors at same origin')
