#include "Online/TunaSweeperOnlineCoopSubsystem.h"
#include "OnlineSubsystem.h"
#include "OnlineSubsystemNames.h"
#include "OnlineSessionSettings.h"
#include "Engine/Engine.h"

void UTunaSweeperOnlineCoopSubsystem::SetState(ETunaSweeperOnlineCoopState S,ETunaSweeperOnlineCoopError E){State=S;OnStateChanged.Broadcast(S,E);}
TSharedPtr<const FUniqueNetId> UTunaSweeperOnlineCoopSubsystem::GetUserId() const{return IdentityInterface.IsValid()?IdentityInterface->GetUniquePlayerId(0):nullptr;}
bool UTunaSweeperOnlineCoopSubsystem::InitializeOnlineCoop(){
 if(bInitialized)return State!=ETunaSweeperOnlineCoopState::Failed;
 SetState(ETunaSweeperOnlineCoopState::Initializing); IOnlineSubsystem* OSS=IOnlineSubsystem::Get(EOS_SUBSYSTEM);
 if(!OSS){SetState(ETunaSweeperOnlineCoopState::Failed,ETunaSweeperOnlineCoopError::SubsystemUnavailable);return false;}
 SessionInterface=OSS->GetSessionInterface(); IdentityInterface=OSS->GetIdentityInterface();
 if(!SessionInterface.IsValid()||!IdentityInterface.IsValid()){SetState(ETunaSweeperOnlineCoopState::Failed,ETunaSweeperOnlineCoopError::SubsystemUnavailable);return false;}
 bInitialized=true; if(IdentityInterface->GetLoginStatus(0)==ELoginStatus::LoggedIn){SetState(ETunaSweeperOnlineCoopState::Ready);return true;}
 SetState(ETunaSweeperOnlineCoopState::Authenticating); LoginHandle=IdentityInterface->AddOnLoginCompleteDelegate_Handle(0,FOnLoginCompleteDelegate::CreateUObject(this,&ThisClass::OnLoginComplete));
 if(!IdentityInterface->AutoLogin(0)){IdentityInterface->ClearOnLoginCompleteDelegate_Handle(0,LoginHandle);SetState(ETunaSweeperOnlineCoopState::Failed,ETunaSweeperOnlineCoopError::AuthenticationFailed);return false;} return true;
}
void UTunaSweeperOnlineCoopSubsystem::OnLoginComplete(int32 N,bool b,const FUniqueNetId&,const FString&){if(LoginHandle.IsValid())IdentityInterface->ClearOnLoginCompleteDelegate_Handle(N,LoginHandle);SetState(b?ETunaSweeperOnlineCoopState::Ready:ETunaSweeperOnlineCoopState::Failed,b?ETunaSweeperOnlineCoopError::None:ETunaSweeperOnlineCoopError::AuthenticationFailed);}
bool UTunaSweeperOnlineCoopSubsystem::CreateHostSession(){if(!InitializeOnlineCoop()||State!=ETunaSweeperOnlineCoopState::Ready||!SessionInterface.IsValid())return false; if(SessionInterface->GetNamedSession(FTunaSweeperOnlineCoopSettings::SessionName()))return false; FRandomStream R(FPlatformTime::Cycles());CurrentInviteCode=TunaSweeperOnlineCoop::GenerateInviteCode(R);FOnlineSessionSettings S;S.NumPublicConnections=FTunaSweeperOnlineCoopSettings::MaxPlayers;S.bShouldAdvertise=true;S.bAllowJoinInProgress=false;S.bIsLANMatch=false;S.Set(FTunaSweeperOnlineCoopSettings::InviteCodeKey(),CurrentInviteCode,EOnlineDataAdvertisementType::ViaOnlineService);S.Set(FTunaSweeperOnlineCoopSettings::ProtocolVersionKey(),FTunaSweeperOnlineCoopSettings::ProtocolVersion,EOnlineDataAdvertisementType::ViaOnlineService);SetState(ETunaSweeperOnlineCoopState::Creating);CreateHandle=SessionInterface->AddOnCreateSessionCompleteDelegate_Handle(FOnCreateSessionCompleteDelegate::CreateUObject(this,&ThisClass::OnCreateComplete));if(!SessionInterface->CreateSession(0,FTunaSweeperOnlineCoopSettings::SessionName(),S)){SessionInterface->ClearOnCreateSessionCompleteDelegate_Handle(CreateHandle);SetState(ETunaSweeperOnlineCoopState::Failed,ETunaSweeperOnlineCoopError::SessionCreateFailed);return false;}return true;}
void UTunaSweeperOnlineCoopSubsystem::OnCreateComplete(FName N,bool b){if(CreateHandle.IsValid())SessionInterface->ClearOnCreateSessionCompleteDelegate_Handle(CreateHandle);if(b){OnInviteCodeReady.Broadcast(CurrentInviteCode);SetState(ETunaSweeperOnlineCoopState::Hosting);}else{CurrentInviteCode.Reset();SetState(ETunaSweeperOnlineCoopState::Failed,ETunaSweeperOnlineCoopError::SessionCreateFailed);}}
bool UTunaSweeperOnlineCoopSubsystem::JoinSessionByInviteCode(const FString& In){if(!InitializeOnlineCoop()||State!=ETunaSweeperOnlineCoopState::Ready)return false;PendingInviteCode=TunaSweeperOnlineCoop::NormalizeInviteCode(In);if(PendingInviteCode.IsEmpty()){SetState(ETunaSweeperOnlineCoopState::Failed,ETunaSweeperOnlineCoopError::InvalidInviteCode);return false;}Search=MakeShared<FOnlineSessionSearch>();Search->MaxSearchResults=20;Search->QuerySettings.Set(FTunaSweeperOnlineCoopSettings::InviteCodeKey(),PendingInviteCode,EOnlineComparisonOp::Equals);SetState(ETunaSweeperOnlineCoopState::Searching);FindHandle=SessionInterface->AddOnFindSessionsCompleteDelegate_Handle(FOnFindSessionsCompleteDelegate::CreateUObject(this,&ThisClass::OnFindComplete));if(!SessionInterface->FindSessions(0,Search.ToSharedRef())){SessionInterface->ClearOnFindSessionsCompleteDelegate_Handle(FindHandle);SetState(ETunaSweeperOnlineCoopState::Failed,ETunaSweeperOnlineCoopError::SessionSearchFailed);return false;}return true;}
void UTunaSweeperOnlineCoopSubsystem::OnFindComplete(bool b){if(FindHandle.IsValid())SessionInterface->ClearOnFindSessionsCompleteDelegate_Handle(FindHandle);if(!b||!Search.IsValid()){SetState(ETunaSweeperOnlineCoopState::Failed,ETunaSweeperOnlineCoopError::SessionSearchFailed);return;}for(const FOnlineSessionSearchResult& R:Search->SearchResults){FString Code;int32 Version=0;R.Session.SessionSettings.Get(FTunaSweeperOnlineCoopSettings::InviteCodeKey(),Code);R.Session.SessionSettings.Get(FTunaSweeperOnlineCoopSettings::ProtocolVersionKey(),Version);const int32 Open=R.Session.NumOpenPublicConnections;if(TunaSweeperOnlineCoop::MatchesSessionMetadata(Code,Version,Open,PendingInviteCode)){SetState(ETunaSweeperOnlineCoopState::Joining);JoinHandle=SessionInterface->AddOnJoinSessionCompleteDelegate_Handle(FOnJoinSessionCompleteDelegate::CreateUObject(this,&ThisClass::OnJoinComplete));if(!SessionInterface->JoinSession(0,FTunaSweeperOnlineCoopSettings::SessionName(),R))SetState(ETunaSweeperOnlineCoopState::Failed,ETunaSweeperOnlineCoopError::JoinFailed);return;}}SetState(ETunaSweeperOnlineCoopState::Failed,ETunaSweeperOnlineCoopError::CodeNotFound);}
void UTunaSweeperOnlineCoopSubsystem::OnJoinComplete(FName N,EOnJoinSessionCompleteResult::Type R){if(JoinHandle.IsValid())SessionInterface->ClearOnJoinSessionCompleteDelegate_Handle(JoinHandle);if(R!=EOnJoinSessionCompleteResult::Success){SetState(ETunaSweeperOnlineCoopState::Failed,ETunaSweeperOnlineCoopError::JoinFailed);return;}FString Address;if(!SessionInterface->GetResolvedConnectString(N,Address)){SetState(ETunaSweeperOnlineCoopState::Failed,ETunaSweeperOnlineCoopError::ResolveConnectStringFailed);return;}if(APlayerController* PC=GetGameInstance()->GetFirstLocalPlayerController()){PC->ClientTravel(Address,ETravelType::TRAVEL_Absolute);SetState(ETunaSweeperOnlineCoopState::Connected);}else SetState(ETunaSweeperOnlineCoopState::Failed,ETunaSweeperOnlineCoopError::TravelFailed);}
void UTunaSweeperOnlineCoopSubsystem::LeaveSession(){if(!SessionInterface.IsValid()){CurrentInviteCode.Reset();SetState(ETunaSweeperOnlineCoopState::Offline);return;}if(SessionInterface->GetNamedSession(FTunaSweeperOnlineCoopSettings::SessionName())){DestroyHandle=SessionInterface->AddOnDestroySessionCompleteDelegate_Handle(FOnDestroySessionCompleteDelegate::CreateUObject(this,&ThisClass::OnDestroyComplete));SessionInterface->DestroySession(FTunaSweeperOnlineCoopSettings::SessionName());}else{CurrentInviteCode.Reset();SetState(ETunaSweeperOnlineCoopState::Ready);}}
void UTunaSweeperOnlineCoopSubsystem::OnDestroyComplete(FName N,bool){if(DestroyHandle.IsValid())SessionInterface->ClearOnDestroySessionCompleteDelegate_Handle(DestroyHandle);CurrentInviteCode.Reset();PendingInviteCode.Reset();++OperationGeneration;SetState(ETunaSweeperOnlineCoopState::Ready);}
