"""Generate the editable, UV-mapped box-level source meshes for the bunker garage door.

All geometry uses the plugin contract: X=width, Y=thickness/depth, Z=height,
centred on the local origin. Every visible metal part owns a distinct cell in a
4x3 base-colour atlas; UE generates a separate lightmap channel during import.
"""

from pathlib import Path


TILE_SIZE_CM = 100.0
ATLAS_COLUMNS = 4
ATLAS_ROWS = 3
ATLAS_PADDING = 0.006
ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "TunaSweeper" / "SourceArt" / "Environment" / "BunkerGarageDoor" / "Models"


def write_box(
    path: Path,
    width: float,
    depth: float,
    height: float,
    atlas_cell: tuple[int, int] | None,
    preserve_face_aspect: bool = False,
) -> None:
    half_width = width * 0.5
    half_depth = depth * 0.5
    half_height = height * 0.5
    vertices = [
        (-half_width, -half_depth, -half_height),
        (half_width, -half_depth, -half_height),
        (half_width, half_depth, -half_height),
        (-half_width, half_depth, -half_height),
        (-half_width, -half_depth, half_height),
        (half_width, -half_depth, half_height),
        (half_width, half_depth, half_height),
        (-half_width, half_depth, half_height),
    ]
    normals = [
        (0.0, 0.0, -1.0),
        (0.0, 0.0, 1.0),
        (0.0, -1.0, 0.0),
        (1.0, 0.0, 0.0),
        (0.0, 1.0, 0.0),
        (-1.0, 0.0, 0.0),
    ]
    face_definitions = [
        ((1, 4, 3, 2), 1, width, depth),
        ((5, 6, 7, 8), 2, width, depth),
        ((1, 2, 6, 5), 3, width, height),
        ((2, 3, 7, 6), 4, depth, height),
        ((3, 4, 8, 7), 5, width, height),
        ((4, 1, 5, 8), 6, depth, height),
    ]

    lines = [
        "# Generated by Tools/GarageDoor/generate_garage_door_objs.py",
        "# X = width, Y = thickness/depth, Z = height; centimetres.",
        f"o {path.stem}",
    ]
    lines.extend(f"v {x:.6f} {y:.6f} {z:.6f}" for x, y, z in vertices)
    lines.extend(f"vn {x:.1f} {y:.1f} {z:.1f}" for x, y, z in normals)

    if atlas_cell is not None:
        column, row = atlas_cell
        u_min = column / ATLAS_COLUMNS + ATLAS_PADDING
        u_max = (column + 1) / ATLAS_COLUMNS - ATLAS_PADDING
        # OBJ's V origin is bottom-left; rows are authored from the top of the PNG.
        v_min = 1.0 - (row + 1) / ATLAS_ROWS + ATLAS_PADDING
        v_max = 1.0 - row / ATLAS_ROWS - ATLAS_PADDING

    uv_index = 1
    face_lines = []
    for vertex_indices, normal_index, u_size, v_size in face_definitions:
        if atlas_cell is None:
            face_uvs = (
                (0.0, 0.0),
                (u_size / TILE_SIZE_CM, 0.0),
                (u_size / TILE_SIZE_CM, v_size / TILE_SIZE_CM),
                (0.0, v_size / TILE_SIZE_CM),
            )
        elif preserve_face_aspect:
            # Atlas cells are square in pixel space even though U/V normalized
            # spans differ on a 4x3 atlas. Fit each face into its cell using its
            # physical aspect ratio so a 45-degree texture remains 45 degrees
            # after mapping onto wide top and narrow side frame pieces.
            longest_side = max(u_size, v_size)
            u_fraction = u_size / longest_side
            v_fraction = v_size / longest_side
            cell_u_center = (column + 0.5) / ATLAS_COLUMNS
            cell_v_center = 1.0 - (row + 0.5) / ATLAS_ROWS
            cell_padding_fraction = ATLAS_PADDING * ATLAS_COLUMNS
            available_u_span = (1.0 - cell_padding_fraction * 2.0) / ATLAS_COLUMNS
            available_v_span = (1.0 - cell_padding_fraction * 2.0) / ATLAS_ROWS
            face_u_span = available_u_span * u_fraction
            face_v_span = available_v_span * v_fraction
            face_u_min = cell_u_center - face_u_span * 0.5
            face_u_max = cell_u_center + face_u_span * 0.5
            face_v_min = cell_v_center - face_v_span * 0.5
            face_v_max = cell_v_center + face_v_span * 0.5
            face_uvs = (
                (face_u_min, face_v_min),
                (face_u_max, face_v_min),
                (face_u_max, face_v_max),
                (face_u_min, face_v_max),
            )
        else:
            face_uvs = (
                (u_min, v_min),
                (u_max, v_min),
                (u_max, v_max),
                (u_min, v_max),
            )
        lines.extend(
            f"vt {u:.6f} {v:.6f}"
            for u, v in face_uvs
        )
        face_vertices = [
            f"{vertex_index}/{uv_index + local_index}/{normal_index}"
            for local_index, vertex_index in enumerate(vertex_indices)
        ]
        face_lines.append("f " + " ".join(face_vertices))
        uv_index += 4

    lines.extend(face_lines)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    OUTPUT.mkdir(parents=True, exist_ok=True)
    meshes = {
        # Top atlas row: three frame pieces receive independent equal-width 45-degree stripe cells.
        "SM_GarageDoor_FrameTop.obj": ((670.0, 45.0, 35.0), (0, 0)),
        "SM_GarageDoor_FrameLeft.obj": ((35.0, 45.0, 390.0), (1, 0)),
        "SM_GarageDoor_FrameRight.obj": ((35.0, 45.0, 390.0), (2, 0)),
        # Middle row: moving panels and independently UV-mapped deployable rails.
        "SM_GarageDoor_UpperPanel.obj": ((600.0, 16.0, 90.0), (0, 1)),
        "SM_GarageDoor_LowerEmbeddedPanel.obj": ((600.0, 16.0, 50.0), (1, 1)),
        "SM_GarageDoor_CanopyRailLeft.obj": ((20.0, 150.0, 20.0), (2, 1)),
        "SM_GarageDoor_CanopyRailRight.obj": ((20.0, 150.0, 20.0), (3, 1)),
        # Bottom row: temporary bunker shell pieces.
        "SM_GarageDoor_TemporaryWallLeft.obj": ((200.0, 45.0, 425.0), (0, 2)),
        "SM_GarageDoor_TemporaryWallRight.obj": ((200.0, 45.0, 425.0), (1, 2)),
        "SM_GarageDoor_TemporaryRoof.obj": ((670.0, 200.0, 45.0), (2, 2)),
        # LED keeps its dedicated emissive material and does not sample this atlas.
        "SM_GarageDoor_LEDBar.obj": ((320.0, 6.0, 10.0), None),
    }
    for filename, (dimensions, atlas_cell) in meshes.items():
        preserve_face_aspect = filename.startswith("SM_GarageDoor_Frame")
        write_box(
            OUTPUT / filename,
            *dimensions,
            atlas_cell,
            preserve_face_aspect=preserve_face_aspect,
        )
        print(f"Wrote {filename}: {dimensions}, atlas_cell={atlas_cell}")


if __name__ == "__main__":
    main()
