"""Generate the editable, UV-mapped box-level source meshes for the bunker garage door.

All geometry uses the plugin contract: X=width, Y=thickness/depth, Z=height,
centred on the local origin. UV0 repeats at one tile per metre; UE generates a
separate lightmap channel during import.
"""

from pathlib import Path


TILE_SIZE_CM = 100.0
ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "TunaSweeper" / "SourceArt" / "Environment" / "BunkerGarageDoor" / "Models"


def write_box(path: Path, width: float, depth: float, height: float) -> None:
    half_width = width * 0.5
    half_depth = depth * 0.5
    half_height = height * 0.5
    vertices = [
        (-half_width, -half_depth, -half_height),
        (half_width, -half_depth, -half_height),
        (half_width, half_depth, -half_height),
        (-half_width, half_depth, -half_height),
        (-half_width, -half_depth, half_height),
        (half_width, -half_depth, half_height),
        (half_width, half_depth, half_height),
        (-half_width, half_depth, half_height),
    ]
    normals = [
        (0.0, 0.0, -1.0),
        (0.0, 0.0, 1.0),
        (0.0, -1.0, 0.0),
        (1.0, 0.0, 0.0),
        (0.0, 1.0, 0.0),
        (-1.0, 0.0, 0.0),
    ]
    face_definitions = [
        ((1, 4, 3, 2), 1, width, depth),
        ((5, 6, 7, 8), 2, width, depth),
        ((1, 2, 6, 5), 3, width, height),
        ((2, 3, 7, 6), 4, depth, height),
        ((3, 4, 8, 7), 5, width, height),
        ((4, 1, 5, 8), 6, depth, height),
    ]

    lines = [
        "# Generated by Tools/GarageDoor/generate_garage_door_objs.py",
        "# X = width, Y = thickness/depth, Z = height; centimetres.",
        f"o {path.stem}",
    ]
    lines.extend(f"v {x:.6f} {y:.6f} {z:.6f}" for x, y, z in vertices)
    lines.extend(f"vn {x:.1f} {y:.1f} {z:.1f}" for x, y, z in normals)

    uv_index = 1
    face_lines = []
    for vertex_indices, normal_index, u_size, v_size in face_definitions:
        u_repeat = u_size / TILE_SIZE_CM
        v_repeat = v_size / TILE_SIZE_CM
        lines.extend(
            [
                "vt 0.000000 0.000000",
                f"vt {u_repeat:.6f} 0.000000",
                f"vt {u_repeat:.6f} {v_repeat:.6f}",
                f"vt 0.000000 {v_repeat:.6f}",
            ]
        )
        face_vertices = [
            f"{vertex_index}/{uv_index + local_index}/{normal_index}"
            for local_index, vertex_index in enumerate(vertex_indices)
        ]
        face_lines.append("f " + " ".join(face_vertices))
        uv_index += 4

    lines.extend(face_lines)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    OUTPUT.mkdir(parents=True, exist_ok=True)
    meshes = {
        "SM_GarageDoor_FrameTop.obj": (670.0, 45.0, 35.0),
        "SM_GarageDoor_FrameLeft.obj": (35.0, 45.0, 390.0),
        "SM_GarageDoor_FrameRight.obj": (35.0, 45.0, 390.0),
        "SM_GarageDoor_UpperPanel.obj": (600.0, 16.0, 90.0),
        "SM_GarageDoor_LowerEmbeddedPanel.obj": (600.0, 16.0, 50.0),
        "SM_GarageDoor_LEDBar.obj": (320.0, 6.0, 10.0),
    }
    for filename, dimensions in meshes.items():
        write_box(OUTPUT / filename, *dimensions)
        print(f"Wrote {filename}: {dimensions}")


if __name__ == "__main__":
    main()
