const ko: Record<string, string> = {
  'exchange.csv': '프로젝트 문자열 CSV 형식 또는 중복 키를 확인하세요.',
  'exchange.notesKo': '개발용 메모 CSV는 string_key,ko 두 열과 한국어만 허용합니다. 번역 대상이 아닙니다.',
  'exchange.source': '프로젝트 퀘스트 원본 형식을 확인하세요.',
  'exchange.metadataMissing': '퀘스트 ID에 해당하는 스튜디오 메타데이터가 없습니다.',
  'exchange.noSnapshots': '가져올 스냅샷이 없습니다.',
  'exchange.response': '서버 응답 형식을 확인할 수 없습니다.',
  'exchange.recoveryConflict': '중단된 교환의 복구 대상이 변경되었습니다. .queststudio-exchange 백업을 확인하세요.',
  'exchange.locked': '다른 퀘스트 교환 작업이 실행 중이거나 잠금 파일 확인이 필요합니다.',
  'exchange.origin': 'HTTPS 퀘스트 스튜디오 주소만 사용할 수 있습니다.',
  'exchange.network': '통신에 실패했습니다. 업로드 중이었다면 재실행 전에 스냅샷 목록을 확인하세요.',
  'exchange.rateLimit': '로그인 시도 제한입니다. {seconds}초 후 다시 실행하세요.',
  'exchange.http': '웹 요청이 실패했습니다. HTTP {status}. 암호 파일과 접근 권한을 확인하세요.',
  'exchange.remoteChanged': '작업 중 최신 스냅샷이 계속 변경되어 가져오기를 중단했습니다.',
  'exchange.localChanged': '작업 중 프로젝트 원본이 변경되어 적용을 중단했습니다.',
  'exchange.usage': '명령: node scripts/quest-exchange.cjs upload 또는 download 또는 initialize',
  'exchange.initialized': '이미 프로젝트 원본이 구성되어 있어 최초 분리를 중단했습니다.',
  'exchange.initializedDone': '로컬 팩에서 {count}개 퀘스트의 원본을 최초 구성했습니다. 백업: {backup}',
  'exchange.empty': '빈 퀘스트 데이터는 업로드하거나 덮어쓰지 않습니다.',
  'exchange.passwordFile': '한 줄 관리자 암호를 지정한 파일에 입력하세요: {path}',
  'exchange.alias': '프로젝트 {time}',
  'exchange.memo': '프로젝트 로컬 SSOT에서 수동 업로드',
  'exchange.uploaded': '새 스냅샷 {id}에 {count}개 퀘스트를 업로드했습니다.',
  'exchange.selected': '가져올 스냅샷: {id}, 최종 수정: {time}, 버전: {revision}',
  'exchange.diff': '정의 수: {before} → {after}, 신규 또는 변경 정의: {changed}개',
  'exchange.downloaded': '정의·좌표·색상을 반영했습니다. 로컬 문자열은 유지했습니다. 백업: {backup}',
  'exchange.logoutFailed': '작업 후 세션 해제에 실패했습니다. 서버 만료 시 자동 해제됩니다.',
  'exchange.failed': '퀘스트 교환에 실패했습니다. 원본 파일·의존성·쓰기 권한을 확인하세요.',
  'app.title': '퀘스트 스튜디오',
  'app.subtitle': '챕터별 흐름과 선행 관계',
  'app.workspace': '작업 공간',
  'app.localFirst': '로컬 원본 · 수동 교환',
  'app.loading': '연결 상태 확인 중…',
  'auth.heading': '작업 공간에 로그인',
  'auth.description': '관리자 비밀번호로 저장된 작업물에 접근합니다.',
  'auth.password': '관리자 비밀번호',
  'auth.login': '로그인',
  'auth.logout': '로그아웃',
  'auth.unconfigured': '관리자 인증이 설정되지 않았습니다. 파일 작업은 계속 사용할 수 있습니다.',
  'auth.localMode': '파일로 작업하기',
  'auth.connect': '관리자 로그인',
  'auth.localHint': '로컬 파일을 가져오면 로그인 없이 그래프를 편집할 수 있습니다.',
  'file.import': '파일 가져오기',
  'file.export': '전체 파일 내보내기',
  'file.imported': '파일을 가져왔습니다. 전체 {count}개 퀘스트를 불러왔습니다.',
  'file.exported': '전체 퀘스트와 문자열을 파일로 내보냈습니다.',
  'file.exportName': 'quest-pack.json',
  'file.choose': '퀘스트 팩 JSON 파일 선택',
  'document.emptyTitle': '퀘스트 팩으로 시작하세요',
  'document.emptyDescription': 'JSON 파일을 직접 가져오거나 저장된 스냅샷을 불러오세요. 모든 챕터와 문자열이 하나의 작업물로 유지됩니다.',
  'document.emptyHint': '시작할 때 데이터를 자동으로 불러오거나 저장하지 않습니다.',
  'document.untitled': '불러온 작업물',
  'document.changed': '저장되지 않은 변경',
  'document.clean': '편집 변경 없음',
  'document.total': '전체 {nodes}개 퀘스트 · {strings}개 문자열',
  'document.replaceTitle': '현재 작업물을 교체할까요?',
  'document.replaceDescription': '내보내거나 스냅샷으로 저장하지 않은 변경은 사라집니다.',
  'document.replace': '교체하기',
  'common.cancel': '취소',
  'common.close': '닫기',
  'common.working': '처리 중…',
  'common.error': '작업을 완료하지 못했습니다',
  'common.dismiss': '알림 닫기',
  'chapter.label': '챕터',
  'chapter.name': '챕터 {chapter}',
  'chapter.count': '표시 {count}개',
  'graph.label': '퀘스트 선행 관계 그래프',
  'graph.print': '인쇄용 PNG',
  'graph.printFilename': '퀘스트-지역-{chapter}.png',
  'graph.printFailed': '인쇄용 이미지를 저장하지 못했습니다. 다시 시도하세요.',
  'graph.legendLocal': '선택 챕터',
  'graph.legendExternal': '다른 지역',
  'graph.noPrerequisites': '선행 없음',
  'graph.linkHandle': '{id} 선행 연결 핸들',
  'graph.linkHelp': '선행으로 지정할 카드에 끌어 놓으세요. Esc로 취소합니다. 숫자 입력도 사용할 수 있습니다.',
  'graph.moveHint': '카드를 드래그해 배치 · Esc로 취소',
  'graph.snapMode': '스냅 모드',
  'graph.snapHelp': '드래그 중 가까운 카드와 가로·세로 위치를 맞춥니다.',
  'graph.arrange': '자동 정렬',
  'graph.arranged': '현재 챕터의 노드를 정렬했습니다. 파일 또는 스냅샷으로 저장하세요.',
  'graph.hint': '카드 드래그로 배치 · 빈 공간으로 이동 · 휠로 확대',
  'graph.zoomIn': '확대',
  'graph.zoomOut': '축소',
  'graph.fit': '전체 보기',
  'graph.zoom': '{percent}%',
  'graph.selectNode': '{id} 상세 보기',
  'graph.noNodes': '이 챕터에는 퀘스트가 없습니다.',
  'inspector.heading': '퀘스트 상세',
  'inspector.empty': '노드를 선택하면 상세 정보와 선행 관계를 볼 수 있습니다.',
  'inspector.description': '게임 설명',
  'inspector.developerNotes': '개발 메모 · 한국어 전용',
  'inspector.developerNotesHint': '게임에 표시되지 않는 개발용 메모입니다. 번역 대상이 아닙니다.',
  'inspector.prerequisiteEvidence': '선행 판단 근거',
  'inspector.cardColor': '카드 바탕 색상',
  'cardColor.default': '기본 회색',
  'cardColor.blue': '청회색',
  'cardColor.green': '녹회색',
  'cardColor.sand': '모래색',
  'cardColor.rose': '장밋빛',
  'cardColor.purple': '보랏빛',
  'validation.cardColor': '카드 바탕 색상은 제공된 색상 중에서 선택하세요.',
  'inspector.prerequisites': '선행 퀘스트',
  'inspector.confirmed': '선행 확인됨',
  'inspector.unspecified': '선행 미정',
  'inspector.unspecifiedHelp': '원문에서 선행조건이 확인되지 않았습니다. 선행 퀘스트가 없다고 확정된 상태는 아닙니다.',
  'inspector.noPrerequisites': '연결된 선행 퀘스트 없음',
  'inspector.numberLabel': '선행 퀘스트 번호',
  'inspector.numberPlaceholder': '예: 21',
  'inspector.numberHelp': '지역과 관계없이 퀘스트 고유번호를 숫자로 입력하세요.',
  'validation.numeric_quest_id': '퀘스트 번호는 1부터 2147483647까지의 정수여야 합니다. JSON에는 문자열이 아닌 숫자로 저장하며, 화면에서는 최소 세 자리로 표시합니다.',
  'inspector.add': '연결',
  'inspector.remove': '{id} 연결 해제',
  'inspector.externalHelp': '다른 지역의 직접 선행 퀘스트입니다. 해당 챕터에서 연결을 편집할 수 있습니다.',
  'inspector.source': '출처 참조',
  'inspector.definition': '전체 퀘스트 정의',
  'inspector.updated': '선행 관계를 변경했습니다.',
  'snapshot.save': '스냅샷 저장',
  'snapshot.overwrite': '스냅샷 덮어쓰기',
  'snapshot.overwriteTitle': '스냅샷을 덮어쓸까요?',
  'snapshot.overwriteDescription': '“{alias}”의 전체 퀘스트와 문자열을 현재 작업물로 교체합니다. 기존 내용은 복구할 수 없습니다.',
  'snapshot.overwritten': '스냅샷을 덮어썼습니다.',
  'snapshot.delete': '삭제',
  'snapshot.deleteTitle': '스냅샷을 삭제할까요?',
  'snapshot.deleteDescription': '“{alias}”를 영구 삭제합니다. 현재 편집 중인 내용은 유지되지만 이 스냅샷에는 덮어쓸 수 없습니다.',
  'snapshot.deleted': '스냅샷을 삭제했습니다. 현재 편집 중인 내용은 유지됩니다.',
  'snapshot.deleteMode': '삭제 모드',
  'snapshot.finishDelete': '삭제 모드 끝내기',
  'snapshot.deleteModeDescription': '삭제할 스냅샷을 선택하세요. 다음 확인 화면에서 삭제를 확정합니다.',
  'snapshot.deletePick': '{alias} 삭제',
  'snapshot.sourceFile': '원본 파일',
  'snapshot.sourceModified': '원본 파일 수정 시각',
  'snapshot.createdAt': '스냅샷 생성 시각',
  'snapshot.updatedAt': '스냅샷 마지막 저장 시각',
  'snapshot.unknown': '알 수 없음',
  'api.snapshot_conflict': '스냅샷이 다른 곳에서 변경되었습니다. 현재 작업물을 새 스냅샷으로 저장하거나 파일로 내보낸 뒤 목록을 새로고침하세요.',
  'snapshot.load': '스냅샷 불러오기',
  'snapshot.saveTitle': '전체 작업물 저장',
  'snapshot.saveDescription': '모든 챕터와 문자열을 새 스냅샷으로 저장합니다. 기존 스냅샷은 유지됩니다.',
  'snapshot.alias': '작업물 이름',
  'snapshot.aliasPlaceholder': '저장할 작업물 이름',
  'snapshot.memo': '메모',
  'snapshot.memoPlaceholder': '이번 저장의 변경 사항 (선택)',
  'snapshot.loadTitle': '저장된 작업물',
  'snapshot.loadDescription': '선택한 스냅샷의 전체 퀘스트와 문자열을 불러옵니다.',
  'snapshot.refresh': '목록 새로고침',
  'snapshot.empty': '저장된 스냅샷이 없습니다.',
  'snapshot.count': '{nodes}개 퀘스트 · {strings}개 문자열',
  'snapshot.saved': '새 스냅샷을 저장했습니다.',
  'snapshot.loaded': '스냅샷 전체를 불러왔습니다.',
  'snapshot.pick': '{alias} 불러오기',
  'client.requestFailed': '서버 응답을 처리하지 못했습니다. 잠시 후 다시 시도하세요.',
  'client.networkError': '서버에 연결하지 못했습니다. 연결 상태를 확인하세요.',
  'client.unexpectedError': '작업 중 오류가 발생했습니다. 다시 시도하세요.',
  'client.invalidJson': '올바른 JSON 파일이 아닙니다.',
  'client.noDocument': '먼저 퀘스트 팩을 가져오세요.',
  'client.noSelection': '편집할 퀘스트를 선택하세요.',
  'client.externalReadOnly': '다른 지역 퀘스트는 해당 챕터에서 편집하세요.',
  'api.unauthorized': '관리자 로그인이 필요합니다.',
  'validation.pack': '퀘스트 팩 형식이 올바르지 않습니다. 버전, 노드, 문자열을 확인하세요.',
  'validation.node': '퀘스트 노드의 정의 또는 저작 정보가 올바르지 않습니다.',
  'validation.string': '문자열 항목의 키, 언어 또는 값이 올바르지 않습니다.',
  'validation.chapter': '{questId}의 챕터 태그를 확인하세요. 챕터는 하나만 지정해야 합니다.',
  'validation.position': '{questId}의 화면 좌표가 올바르지 않습니다.',
  'validation.duplicate_quest': '퀘스트 번호 {questId}가 중복되었습니다.',
  'validation.duplicate_string': '문자열 {stringKey}의 {locale} 항목이 중복되었습니다.',
  'validation.missing_string': '한국어 문자열 {stringKey}를 찾을 수 없습니다.',
  'validation.unknown_quest': '퀘스트 번호 {questId}를 찾을 수 없습니다.',
  'validation.self_reference': '{questId}는 자기 자신을 선행 퀘스트로 연결할 수 없습니다.',
  'validation.duplicate_prerequisite': '{questId}는 이미 선행 퀘스트로 연결되어 있습니다.',
  'validation.cycle': '선행 관계가 순환하게 됩니다. 연결을 다시 확인하세요.',
  'api.not_found': '요청한 작업물을 찾을 수 없습니다.',
  'api.forbidden_origin': '허용되지 않은 출처의 요청입니다. 원래 작업 공간에서 다시 시도하세요.',
  'api.secure_transport_required': '관리자 로그인에는 보안 연결이 필요합니다.',
  'api.authentication_not_configured': '관리자 인증이 설정되지 않았습니다.',
  'api.too_many_login_attempts': '로그인 시도가 너무 많습니다. {retryAfter}초 후 다시 시도하세요.',
  'api.invalid_credentials': '관리자 비밀번호가 올바르지 않습니다.',
  'api.unsupported_media_type': '지원하지 않는 요청 형식입니다.',
  'api.payload_too_large': '작업물의 크기가 서버에서 허용하는 한도를 넘었습니다.',
  'api.invalid_json': '요청한 JSON 데이터를 처리할 수 없습니다.',
  'api.invalid_snapshot': '작업물 이름과 메모를 확인하세요.',
  'api.internal_error': '서버에서 작업을 완료하지 못했습니다. 잠시 후 다시 시도하세요.',
};

export function t(key: string, params: Record<string, string | number> = {}): string {
  const value = ko[key] ?? ko['client.unexpectedError']!;
  return value.replace(/\{(\w+)\}/g, (match, name: string) => name in params ? String(params[name]) : match);
}
